name: Docker Build

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [
          'allurecmd-groovy/Dockerfile',
          'kubectl-helm-helmfile/Dockerfile',
          'maven-chrome/Dockerfile',
          'soapui-groovy/Dockerfile',
        ]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t test-image -f ${{ matrix.dockerfile }} $(dirname ${{ matrix.dockerfile }})