name: Docker Build

on:
  push:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        dockerfile: [
          'allurecmd-groovy/Dockerfile',
          'kubectl-helm-helmfile/Dockerfile',
          'maven-chrome/Dockerfile',
          'soapui-groovy/Dockerfile',
        ]
    
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}

      - name: Build Docker image
        run: |
          docker build -t test-image:${{ github.sha }} -f ${{ matrix.dockerfile }} $(dirname ${{ matrix.dockerfile }})

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image:${{ github.sha }}'
          format: 'table'
          exit-code: '0'